name: build and push container

on:
  workflow_dispatch:

jobs:
  build:

    name: create docker container
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker build . --file Dockerfile --tag johnstok815/gitdock:latest

      - name: Push docker images
        run: |
          docker login -u johnstok815 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push johnstok815/gitdock:latest

